spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  web:
    resources:
      static-locations: file:C:/YoutubeClone/videos


videos:
  path: static/videos


directory:
  path: C:/YoutubeClone/videos


ffmpeg:
  path: C:/FFmpeg/ffmpeg-master-latest-win64-gpl/bin