server:
  port: 8081





spring:


  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:mysql://localhost:3306/video}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:mysql}
    pool:
      max-size: 10





  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:update}
    show-sql: ${SPRING_JPA_SHOW-SQL:true}





  application:
    name: VIDEO-SERVICE


  profiles:
    active: eureka,files-serve,graphql,logger