spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  web:
    resources:
      static-locations: file:${FILES_DIR_PATH:C:/YoutubeClone/videos}


videos:
  path: static/videos


directory:
  path: ${FILES_DIR_PATH:C:/YoutubeClone/videos}