server:
  port: 9050




spring:
  application:
    name: API-GATEWAY


  main:
    allow-circular-references: true





  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**,/check






#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:9000/eureka

eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER-IP-ADDRESS:true}
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER-WITH-EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH-REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://localhost:9000/eureka}