pipeline {
    agent any

    environment {
        SONAR_TOKEN = "3aebdfa2305f597ecbf8f85126333461d273673e"
    }

    stages { 
        

        stage('SonarCloud Analysis') {
            steps { 


                // Change directory to the UserService project

                dir('microservices/UserService') {
                    script { 

                        // Run Gradle with Sonar analysis 
                        bat './gradlew sonar -Dsonar.login=${SONAR_TOKEN}'
                    }
                }
                
            }
        }
    }


    post {
            success {
                // You can add any post-deployment steps or notifications here
                echo 'Deployment successful!'
            }
            failure {
                // Handle deployment failures here
                echo 'Deployment failed!'
            }
    }
}