pipeline {
    agent any

    environment {
        SONAR_TOKEN = "3aebdfa2305f597ecbf8f85126333461d273673e"
    }

    stages { 
        

        stage('SonarCloud Analysis') {
            steps { 


                // Change directory to the UserService project

                dir('microservices/UserService') {
                    script { 

                        // Run Gradle with SonarQube analysis

                        sh './gradlew sonarqube -Dsonar.projectKey=Afshal-Hassan_VideoStream -Dsonar.organization=afshal1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=99b8147a4f5d12b75dbb6a92d7f1afa16c7fb3bd'
                    }
                }
                
            }
        }
    }


    post {
            success {
                // You can add any post-deployment steps or notifications here
                echo 'Deployment successful!'
            }
            failure {
                // Handle deployment failures here
                echo 'Deployment failed!'
            }
    }
}